<a href="https://colab.research.google.com/github/Jeremy-Thompson33/BaseballSimulator/blob/main/BaseballSimulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Baseball Simulation

### Introduction
In this notebook I will be creating a baseball game simulator with real player statistics to help answer strategical questions. I will web scrape updated player statistics from various dynamic websites using Selenium. I will then clean the data from these sites and merge the data that is necessary for simulation into a single master table. When the data is ready, I will prepare a lineup using a Player class and run a simulation using the lineup.

## Import Data

In [1]:
# Import packages
import pandas as pd
import numpy as np
import random
import time

### Set Up Selenium

In [2]:
# Update package list
!apt-get update

# Install Chromium and its driver
!apt-get install -y chromium-browser chromium-chromedriver

# Install Selenium
!pip install selenium

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:5 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2,986 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,250 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,296 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,557 kB]
Get:15 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [79.8 kB]
Get:16 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [1,778 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,747 kB]
Get:18 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,040 kB]
Fetched 23.1 MB in 5s (4,984 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  apparmor libfuse3-3 libudev1 snapd squashfs-tools systemd-hwe-hwdb udev
Suggested packages:
  apparmor-profiles-extra apparmor-utils fuse3 zenity | kdialog
The following NEW packages will be installed:
  apparmor chromium-browser chromium-chromedriver libfuse3-3 snapd
  squashfs-tools systemd-hwe-hwdb udev
The following packages will be upgraded:
  libudev1
1 upgraded, 8 newly installed, 0 to remove and 45 not upgraded.
Need to get 30.3 MB of archives.
After this operation, 123 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 apparmor amd64 3.0.4-2ubuntu2.4 [598 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 squashfs-tools amd64 1:4.5-3build1 [159 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libudev1 amd64 249.11-0ubuntu3.16 [76.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 udev amd64 249.11-0ubuntu3.16 [1,557 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libfuse3-3 amd64 3.10.5-1build1 [81.2 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 snapd amd64 2.67.1+22.04 [27.8 MB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 chromium-browser amd64 1:85.0.4183.83-0ubuntu2.22.04.1 [49.2 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 chromium-chromedriver amd64 1:85.0.4183.83-0ubuntu2.22.04.1 [2,308 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 systemd-hwe-hwdb all 249.11.5 [3,228 B]
Fetched 30.3 MB in 1s (45.7 MB/s)
Preconfiguring packages ...
Selecting previously unselected package apparmor.
(Reading database ... 126111 files and directories currently installed.)
Preparing to unpack .../apparmor_3.0.4-2ubuntu2.4_amd64.deb ...
Unpacking apparmor (3.0.4-2ubuntu2.4) ...
Selecting previously unselected package squashfs-tools.
Preparing to unpack .../squashfs-tools_1%3a4.5-3build1_amd64.deb ...
Unpacking squashfs-tools (1:4.5-3build1) ...
Preparing to unpack .../libudev1_249.11-0ubuntu3.16_amd64.deb ...
Unpacking libudev1:amd64 (249.11-0ubuntu3.16) over (249.11-0ubuntu3.12) ...
Setting up libudev1:amd64 (249.11-0ubuntu3.16) ...
Selecting previously unselected package udev.
(Reading database ... 126311 files and directories currently installed.)
Preparing to unpack .../udev_249.11-0ubuntu3.16_amd64.deb ...
Unpacking udev (249.11-0ubuntu3.16) ...
Selecting previously unselected package libfuse3-3:amd64.
Preparing to unpack .../libfuse3-3_3.10.5-1build1_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.10.5-1build1) ...
Selecting previously unselected package snapd.
Preparing to unpack .../snapd_2.67.1+22.04_amd64.deb ...
Unpacking snapd (2.67.1+22.04) ...
Setting up apparmor (3.0.4-2ubuntu2.4) ...
Created symlink /etc/systemd/system/sysinit.target.wants/apparmor.service → /lib/systemd/system/apparmor.service.
Setting up squashfs-tools (1:4.5-3build1) ...
Setting up udev (249.11-0ubuntu3.16) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libfuse3-3:amd64 (3.10.5-1build1) ...
Setting up snapd (2.67.1+22.04) ...
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.apparmor.service → /lib/systemd/system/snapd.apparmor.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.autoimport.service → /lib/systemd/system/snapd.autoimport.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.core-fixup.service → /lib/systemd/system/snapd.core-fixup.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.recovery-chooser-trigger.service → /lib/systemd/system/snapd.recovery-chooser-trigger.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.seeded.service → /lib/systemd/system/snapd.seeded.service.
Created symlink /etc/systemd/system/cloud-final.service.wants/snapd.seeded.service → /lib/systemd/system/snapd.seeded.service.
Unit /lib/systemd/system/snapd.seeded.service is added as a dependency to a non-existent unit cloud-final.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.service → /lib/systemd/system/snapd.service.
Created symlink /etc/systemd/system/timers.target.wants/snapd.snap-repair.timer → /lib/systemd/system/snapd.snap-repair.timer.
Created symlink /etc/systemd/system/sockets.target.wants/snapd.socket → /lib/systemd/system/snapd.socket.
Created symlink /etc/systemd/system/final.target.wants/snapd.system-shutdown.service → /lib/systemd/system/snapd.system-shutdown.service.
Selecting previously unselected package chromium-browser.
(Reading database ... 126540 files and directories currently installed.)
Preparing to unpack .../chromium-browser_1%3a85.0.4183.83-0ubuntu2.22.04.1_amd64.deb ...
=> Installing the chromium snap
==> Checking connectivity with the snap store
===> System doesn't have a working snapd, skipping
Unpacking chromium-browser (1:85.0.4183.83-0ubuntu2.22.04.1) ...
Selecting previously unselected package chromium-chromedriver.
Preparing to unpack .../chromium-chromedriver_1%3a85.0.4183.83-0ubuntu2.22.04.1_amd64.deb ...
Unpacking chromium-chromedriver (1:85.0.4183.83-0ubuntu2.22.04.1) ...
Selecting previously unselected package systemd-hwe-hwdb.
Preparing to unpack .../systemd-hwe-hwdb_249.11.5_all.deb ...
Unpacking systemd-hwe-hwdb (249.11.5) ...
Setting up systemd-hwe-hwdb (249.11.5) ...
Setting up chromium-browser (1:85.0.4183.83-0ubuntu2.22.04.1) ...
update-alternatives: using /usr/bin/chromium-browser to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/chromium-browser to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
Setting up chromium-chromedriver (1:85.0.4183.83-0ubuntu2.22.04.1) ...
Processing triggers for udev (249.11-0ubuntu3.16) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Processing triggers for dbus (1.12.20-2ubuntu4.1) ...
Collecting selenium
  Downloading selenium-4.33.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: urllib3~=2.4.0 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]~=2.4.0->selenium) (2.4.0)
Collecting trio~=0.30.0 (from selenium)
  Downloading trio-0.30.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: certifi>=2025.4.26 in /usr/local/lib/python3.11/dist-packages (from selenium) (2025.4.26)
Collecting typing_extensions~=4.13.2 (from selenium)
  Downloading typing_extensions-4.13.2-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: websocket-client~=1.8.0 in /usr/local/lib/python3.11/dist-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (3.10)
Collecting outcome (from trio~=0.30.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket~=0.12.2->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]~=2.4.0->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from wsproto>=0.14->trio-websocket~=0.12.2->selenium) (0.16.0)
Downloading selenium-4.33.0-py3-none-any.whl (9.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 58.1 MB/s eta 0:00:00
Downloading trio-0.30.0-py3-none-any.whl (499 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.2/499.2 kB 32.0 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 3.2 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, typing_extensions, outcome, trio, trio-websocket, selenium
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.14.0
    Uninstalling typing_extensions-4.14.0:
      Successfully uninstalled typing_extensions-4.14.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
typeguard 4.4.3 requires typing_extensions>=4.14.0, but you have typing-extensions 4.13.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed outcome-1.3.0.post0 selenium-4.33.0 trio-0.30.0 trio-websocket-0.12.2 typing_extensions-4.13.2 wsproto-1.2.0

In [3]:
# Import Selenium packages
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [4]:
# Set up headless Chrome options
options = Options()
options.add_argument('--headless')  # Run in headless mode
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

### Web Scrape Individual Hitting Stats Against LHP

In [5]:
# Initialize WebDriver
driver = webdriver.Chrome(options=options)

# Get URL
url = 'https://www.mlb.com/stats/?split=vl'
driver.get(url)

# Get table
table = driver.find_element(By.XPATH, '//*[@id="stats-app-root"]/section/section/div[4]/div[1]/div/table')

# Extract headers from the table
headers = table.find_elements(By.TAG_NAME, 'th')[0:18]

# Clean headers
headers_data = [h.text for h in headers]

# Print headers
print(headers_data)

['PLAYER', 'TEAM', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB', 'CS', 'AVG', 'OBP', 'SLG', 'OPS']

In [6]:
"""Gets and returns the first player name in the table"""
def get_first_player_name(driver):
    table = driver.find_element(By.XPATH, '//*[@id="stats-app-root"]/section/section/div[4]/div[1]/div/table')
    rows = table.find_elements(By.TAG_NAME, "tr")[1:]  # Skip header
    if not rows:
        return None
    try:
        player_cell = rows[0].find_element(By.TAG_NAME, 'a')
        return player_cell.get_attribute('aria-label').strip()
    except:
        return None

In [7]:
# Define the specific columns wwanted
desired_columns = ['TEAM', 'AB', 'H', '2B', '3B', 'HR', 'BB', 'SO', 'AVG', 'OBP', 'SLG']

# Get indices of desired columns
desired_indices = [(headers_data.index(col) - 1) for col in desired_columns]

In [8]:
# Extract data

all_data = []
wait = WebDriverWait(driver, 10)
previous_first_player = None

while True:
    # Re-locate table and get rows
    table = driver.find_element(By.XPATH, '//*[@id="stats-app-root"]/section/section/div[4]/div[1]/div/table')
    rows = table.find_elements(By.TAG_NAME, 'tr')[1:]  # Skip header

    # Get the first player name in the table
    current_first_player = get_first_player_name(driver)

    # If same first player as previous page, no new data then exit
    if current_first_player == previous_first_player and previous_first_player is not None:
        print('No new page detected, exiting.')
        break

    previous_first_player = current_first_player

    # Append data from rows into all_data list
    for row in rows:
        player_name =  row.find_element(By.TAG_NAME, 'a').get_attribute('aria-label').strip()
        cells = row.find_elements(By.TAG_NAME, 'td')
        if len(cells) == len(headers_data) - 1:
            row_data = [cells[i].text for i in desired_indices]
            row_data.insert(0, player_name)
            all_data.append(row_data)

    # Click Next button
    try:
        button = wait.until(EC.element_to_be_clickable((By.XPATH, '//button[@aria-label="next page button"]')))
        driver.execute_script('arguments[0].scrollIntoView(true);', button)
        time.sleep(1)
        driver.execute_script('arguments[0].click();', button)

        # Wait until the first player's name changes / new page loads
        wait.until(lambda d: get_first_player_name(d) != current_first_player)

        time.sleep(1)  # extra small delay to be safe
    except:
        print('Could not click next button or no more pages.')
        break


LHP_hitting_stats_df = pd.DataFrame(all_data, columns=['Player'] + desired_columns)
print(LHP_hitting_stats_df.head())
driver.quit()

Could not click next button or no more pages.
           Player TEAM  AB   H 2B 3B  HR  BB  SO   AVG   OBP   SLG
0  Kyle Schwarber  PHI  93  25  2  1  11  19  29  .269  .409  .667
1     Aaron Judge  NYY  56  21  4  0   9  17  17  .375  .521  .929
2     Cal Raleigh  SEA  81  24  4  0   8   6  29  .296  .352  .642
3    Seiya Suzuki  CHC  69  23  4  0   8  11  18  .333  .420  .739
4   Manny Machado   SD  73  22  3  0   7   9  17  .301  .373  .630

### Web Scrape Individual Hitting Stats Against RHP

In [9]:
# Initialize WebDriver
driver = webdriver.Chrome(options=options)

In [10]:
# Get URL
url = 'https://www.mlb.com/stats/?split=vr'
driver.get(url)

# Get table
table = driver.find_element(By.XPATH, '//*[@id="stats-app-root"]/section/section/div[4]/div[1]/div/table')

# Extract headers from the table
headers = table.find_elements(By.TAG_NAME, 'th')[0:18]

# Clean headers
headers_data = [h.text for h in headers]

# Print headers
print(headers_data)

['PLAYER', 'TEAM', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB', 'CS', 'AVG', 'OBP', 'SLG', 'OPS']

In [11]:
# Define the specific columns you want
desired_columns = ['TEAM', 'AB', 'H', '2B', '3B', 'HR', 'BB', 'SO', 'AVG', 'OBP', 'SLG']

# Get indices of desired columns
desired_indices = [(headers_data.index(col) - 1) for col in desired_columns]

In [12]:
# Extract data
all_data = []
wait = WebDriverWait(driver, 10)
previous_first_player = None

while True:
    # Re-locate table and get rows
    table = driver.find_element(By.XPATH, '//*[@id="stats-app-root"]/section/section/div[4]/div[1]/div/table')
    rows = table.find_elements(By.TAG_NAME, 'tr')[1:]  # Skip header

    # Get the first player name in the table
    current_first_player = get_first_player_name(driver)

    # If same first player as previous page, no new data then exit
    if current_first_player == previous_first_player and previous_first_player is not None:
        print('No new page detected, exiting.')
        break

    previous_first_player = current_first_player

    # Append data from rows into all_data list
    for row in rows:
        player_name = row.find_element(By.TAG_NAME, 'a').get_attribute('aria-label').strip()
        cells = row.find_elements(By.TAG_NAME, 'td')
        if len(cells) == len(headers_data) - 1:
            row_data = [cells[i].text for i in desired_indices]
            row_data.insert(0, player_name)
            all_data.append(row_data)

    # Click Next button
    try:
        button = wait.until(EC.element_to_be_clickable((By.XPATH, '//button[@aria-label="next page button"]')))
        driver.execute_script('arguments[0].scrollIntoView(true);', button)
        time.sleep(1)
        driver.execute_script('arguments[0].click();', button)

        # Wait until the first player's name changes / new page loads
        wait.until(lambda d: get_first_player_name(d) != current_first_player)

        time.sleep(1)  # extra small delay to be safe
    except:
        print('Could not click next button or no more pages.')
        break


RHP_hitting_stats_df = pd.DataFrame(all_data, columns=['Player'] + desired_columns)
print(RHP_hitting_stats_df.head())
driver.quit()

Could not click next button or no more pages.
           Player TEAM   AB   H  2B 3B  HR  BB  SO   AVG   OBP   SLG
0   Shohei Ohtani  LAD  183  53   6  2  21  41  54  .290  .419  .689
1     Cal Raleigh  SEA  178  43   8  0  18  36  50  .242  .376  .590
2  Eugenio Suárez   AZ  199  52  10  0  18  12  58  .261  .326  .583
3  Corbin Carroll   AZ  199  52  11  6  17  21  57  .261  .344  .633
4     Aaron Judge  NYY  209  79  13  2  17  30  61  .378  .461  .703

### Web Scrape for Advanced Hitting Statistics

In [13]:
# Initialize WebDriver
driver = webdriver.Chrome(options=options)

# Get website URL
url = 'https://baseballsavant.mlb.com/leaderboard/batted-ball?gameType=Regular&minSwings=25&minGroupSwings=1&seasonStart=2025&seasonEnd=2025&type=batter'
driver.get(url)

In [14]:
# Locate the table by its class name
table = driver.find_element(By.CLASS_NAME, 'table-savant')

In [15]:
# Extract headers from the table
headers = table.find_elements(By.TAG_NAME, 'th')[6:24]

# Clean headers
headers_data = [h.text.replace(' ', '').replace('\n', '') for h in headers]

# Print headers
print(headers_data)

['Rk.', 'Player', 'Team', 'BBE', 'GB%', 'AIR%', 'FB%', 'LD%', 'PU%', 'Pull%', 'Straight%', 'Oppo%', 'PullGB%', 'StraightGB%', 'OppoGB%', 'PullAIR%', 'StraightAIR%', 'OppoAIR%']

In [16]:
# Extract all the rows from the table
rows = table.find_elements(By.CLASS_NAME, 'default-table-row')

# Extract data from rows and add it to the data list
data = []

for row in rows:
    row_data = row.find_elements(By.TAG_NAME, 'td')
    individual_row_data = [cell.text.strip() for cell in row_data]
    data.append(individual_row_data)

# Create DataFrame with headers and data lists
batted_ball_event_df = pd.DataFrame(data, columns=headers_data)

# Print dataframe
batted_ball_event_df.head()

,Rk.,Player,Team,BBE,GB%,AIR%,FB%,LD%,PU%,Pull%,Straight%,Oppo%,PullGB%,StraightGB%,OppoGB%,PullAIR%,StraightAIR%,OppoAIR%
0,1,"Melendez, MJ",,27,33.3%,66.7%,29.6%,18.5%,18.5%,63.0%,29.6%,7.4%,22.2%,11.1%,0.0%,40.7%,18.5%,7.4%
1,2,"Raleigh, Cal",,181,24.9%,75.1%,40.3%,22.7%,12.2%,51.9%,29.8%,18.2%,14.4%,7.7%,2.8%,37.6%,22.1%,15.5%
2,3,"Pérez, Wenceel",,44,25.0%,75.0%,40.9%,25.0%,9.1%,47.7%,25.0%,27.3%,11.4%,13.6%,0.0%,36.4%,11.4%,27.3%
3,4,"Paredes, Isaac",,205,33.2%,66.8%,32.7%,26.8%,7.3%,54.6%,28.8%,16.6%,19.5%,7.8%,5.9%,35.1%,21.0%,10.7%
4,5,"Suwinski, Jack",,20,25.0%,75.0%,35.0%,40.0%,0.0%,45.0%,30.0%,25.0%,10.0%,10.0%,5.0%,35.0%,20.0%,20.0%

### Web Scrape for Plate Appearances

In [17]:
# Get URL
url = 'https://www.baseball-reference.com/leagues/majors/2025-standard-batting.shtml'
driver.get(url)

In [18]:
# Get table
table = driver.find_element(By.ID, 'players_standard_batting')

# Extract headers
headers = [th.text for th in table.find_elements(By.XPATH, './/thead/tr[1]/th')]

In [19]:
# Get desired columns
desired_columns = ['Player', 'PA']

# Get  indices for the desired columns
desired_indices = [headers.index(col) - 1 for col in desired_columns]

In [20]:
# Extract data
rows = table.find_elements(By.XPATH, './/tbody/tr[not(contains(@class, "thead"))]')

data = []
for row in rows:
    cells = row.find_elements(By.TAG_NAME, 'td')
    row_data = [cells[i].text for i in desired_indices]
    data.append(row_data)

plate_app_df = pd.DataFrame(data, columns=desired_columns)

driver.quit()

print(plate_app_df.head())

           Player   PA
0   Jarren Duran*  339
1  Rafael Devers*  334
2  Shohei Ohtani*  331
3    Brent Rooker  324
4     Bo Bichette  321

## Clean Data

### Clean LHP Hitting Stats Dataframe

In [21]:
# Change header names
LHP_hitting_stats_df.columns = ['Player'] + ['Team'] + [col + '_LHP' if not col.endswith('LHP') else col for col in LHP_hitting_stats_df.columns[2:]]

# Print dataframe
print(LHP_hitting_stats_df.head())

           Player Team AB_LHP H_LHP 2B_LHP 3B_LHP HR_LHP BB_LHP SO_LHP  \
0  Kyle Schwarber  PHI     93    25      2      1     11     19     29
1     Aaron Judge  NYY     56    21      4      0      9     17     17
2     Cal Raleigh  SEA     81    24      4      0      8      6     29
3    Seiya Suzuki  CHC     69    23      4      0      8     11     18
4   Manny Machado   SD     73    22      3      0      7      9     17

  AVG_LHP OBP_LHP SLG_LHP
0    .269    .409    .667
1    .375    .521    .929
2    .296    .352    .642
3    .333    .420    .739
4    .301    .373    .630

In [22]:
# Change datatypes of columns
for col in LHP_hitting_stats_df.columns[2:]:
    LHP_hitting_stats_df[col] = (pd.to_numeric(LHP_hitting_stats_df[col], errors='coerce'))

# Print dataframe
print(LHP_hitting_stats_df.head())

           Player Team  AB_LHP  H_LHP  2B_LHP  3B_LHP  HR_LHP  BB_LHP  SO_LHP  \
0  Kyle Schwarber  PHI      93     25       2       1      11      19      29
1     Aaron Judge  NYY      56     21       4       0       9      17      17
2     Cal Raleigh  SEA      81     24       4       0       8       6      29
3    Seiya Suzuki  CHC      69     23       4       0       8      11      18
4   Manny Machado   SD      73     22       3       0       7       9      17

   AVG_LHP  OBP_LHP  SLG_LHP
0    0.269    0.409    0.667
1    0.375    0.521    0.929
2    0.296    0.352    0.642
3    0.333    0.420    0.739
4    0.301    0.373    0.630

### Clean RHP Hitting Stats Dataframe

In [23]:
# Change header names
RHP_hitting_stats_df.columns = ['Player'] + ['Team'] + [col + '_RHP' if not col.endswith('RHP') else col for col in RHP_hitting_stats_df.columns[2:]]

# Print dataframe
print(RHP_hitting_stats_df.head())

           Player Team AB_RHP H_RHP 2B_RHP 3B_RHP HR_RHP BB_RHP SO_RHP  \
0   Shohei Ohtani  LAD    183    53      6      2     21     41     54
1     Cal Raleigh  SEA    178    43      8      0     18     36     50
2  Eugenio Suárez   AZ    199    52     10      0     18     12     58
3  Corbin Carroll   AZ    199    52     11      6     17     21     57
4     Aaron Judge  NYY    209    79     13      2     17     30     61

  AVG_RHP OBP_RHP SLG_RHP
0    .290    .419    .689
1    .242    .376    .590
2    .261    .326    .583
3    .261    .344    .633
4    .378    .461    .703

In [24]:
# Change datatypes of columns
for col in RHP_hitting_stats_df.columns[2:]:
    RHP_hitting_stats_df[col] = (pd.to_numeric(RHP_hitting_stats_df[col], errors='coerce'))

# Print dataframe
print(RHP_hitting_stats_df.head())

           Player Team  AB_RHP  H_RHP  2B_RHP  3B_RHP  HR_RHP  BB_RHP  SO_RHP  \
0   Shohei Ohtani  LAD     183     53       6       2      21      41      54
1     Cal Raleigh  SEA     178     43       8       0      18      36      50
2  Eugenio Suárez   AZ     199     52      10       0      18      12      58
3  Corbin Carroll   AZ     199     52      11       6      17      21      57
4     Aaron Judge  NYY     209     79      13       2      17      30      61

   AVG_RHP  OBP_RHP  SLG_RHP
0    0.290    0.419    0.689
1    0.242    0.376    0.590
2    0.261    0.326    0.583
3    0.261    0.344    0.633
4    0.378    0.461    0.703

### Clean Batted Ball Event Dataframe

In [25]:
# Drop uneccesary columns
batted_ball_event_df.drop('Rk.', axis=1, inplace=True)

batted_ball_event_df.drop('Team', axis=1, inplace=True)

In [26]:
# Change format of 'Player' column
batted_ball_event_df['Player'] = batted_ball_event_df['Player'].apply(lambda x: x.split(', ')[1] + ' ' + x.split(', ')[0] if ', ' in x else x)

# Print dataframe
batted_ball_event_df.head()

,Player,BBE,GB%,AIR%,FB%,LD%,PU%,Pull%,Straight%,Oppo%,PullGB%,StraightGB%,OppoGB%,PullAIR%,StraightAIR%,OppoAIR%
0,MJ Melendez,27,33.3%,66.7%,29.6%,18.5%,18.5%,63.0%,29.6%,7.4%,22.2%,11.1%,0.0%,40.7%,18.5%,7.4%
1,Cal Raleigh,181,24.9%,75.1%,40.3%,22.7%,12.2%,51.9%,29.8%,18.2%,14.4%,7.7%,2.8%,37.6%,22.1%,15.5%
2,Wenceel Pérez,44,25.0%,75.0%,40.9%,25.0%,9.1%,47.7%,25.0%,27.3%,11.4%,13.6%,0.0%,36.4%,11.4%,27.3%
3,Isaac Paredes,205,33.2%,66.8%,32.7%,26.8%,7.3%,54.6%,28.8%,16.6%,19.5%,7.8%,5.9%,35.1%,21.0%,10.7%
4,Jack Suwinski,20,25.0%,75.0%,35.0%,40.0%,0.0%,45.0%,30.0%,25.0%,10.0%,10.0%,5.0%,35.0%,20.0%,20.0%

In [27]:
# Change format of columns containing percent symbols
for col in batted_ball_event_df.columns:
    if batted_ball_event_df[col].dtype == 'object' and batted_ball_event_df[col].str.contains('%').any():
        batted_ball_event_df[col] = (pd.to_numeric(batted_ball_event_df[col].str.replace('%', '', regex=False), errors='coerce') / 100).round(3)

# Print dataframe
batted_ball_event_df.head()

,Player,BBE,GB%,AIR%,FB%,LD%,PU%,Pull%,Straight%,Oppo%,PullGB%,StraightGB%,OppoGB%,PullAIR%,StraightAIR%,OppoAIR%
0,MJ Melendez,27,0.333,0.667,0.296,0.185,0.185,0.630,0.296,0.074,0.222,0.111,0.000,0.407,0.185,0.074
1,Cal Raleigh,181,0.249,0.751,0.403,0.227,0.122,0.519,0.298,0.182,0.144,0.077,0.028,0.376,0.221,0.155
2,Wenceel Pérez,44,0.250,0.750,0.409,0.250,0.091,0.477,0.250,0.273,0.114,0.136,0.000,0.364,0.114,0.273
3,Isaac Paredes,205,0.332,0.668,0.327,0.268,0.073,0.546,0.288,0.166,0.195,0.078,0.059,0.351,0.210,0.107
4,Jack Suwinski,20,0.250,0.750,0.350,0.400,0.000,0.450,0.300,0.250,0.100,0.100,0.050,0.350,0.200,0.200

### Clean Plate Appearance Dataframe

In [28]:
# Clean player column
plate_app_df["Player"] = plate_app_df["Player"].str.replace(r"[*#?]+$", "", regex=True)

### Merge Dataframes

In [29]:
# Left merge dataframes on 'Player' column
master_hitting_stats_df = RHP_hitting_stats_df.merge(LHP_hitting_stats_df, how='left', on='Player').merge(batted_ball_event_df, how='left', on='Player').merge(plate_app_df, how='left', on='Player')

# Print dataframe sample
master_hitting_stats_df.sample(5)

,Player,Team_x,AB_RHP,H_RHP,2B_RHP,3B_RHP,HR_RHP,BB_RHP,SO_RHP,AVG_RHP,...,Pull%,Straight%,Oppo%,PullGB%,StraightGB%,OppoGB%,PullAIR%,StraightAIR%,OppoAIR%,PA
133,Brooks Lee,MIN,131,36,4,0,6,9,22,0.275,...,0.420,0.325,0.255,0.210,0.134,0.051,0.210,0.191,0.204,208
563,Ben Rortvedt,TB,56,4,1,0,0,7,13,0.071,...,0.408,0.265,0.327,0.245,0.163,0.082,0.163,0.102,0.245,70
111,Jacob Wilson,ATH,219,78,11,0,7,10,15,0.356,...,0.337,0.431,0.231,0.192,0.275,0.078,0.145,0.157,0.153,289
551,Pablo Reyes,NYY,15,4,1,0,0,0,5,0.267,...,0.227,0.455,0.318,0.227,0.227,0.045,0.000,0.227,0.273,34
49,Max Muncy,LAD,168,47,8,1,9,37,47,0.280,...,0.484,0.357,0.159,0.204,0.127,0.006,0.280,0.229,0.153,116

In [30]:
master_hitting_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 619 entries, 0 to 618
Data columns (total 39 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Player        619 non-null    object
 1   Team_x        619 non-null    object
 2   AB_RHP        619 non-null    int64
 3   H_RHP         619 non-null    int64
 4   2B_RHP        619 non-null    int64
 5   3B_RHP        619 non-null    int64
 6   HR_RHP        619 non-null    int64
 7   BB_RHP        619 non-null    int64
 8   SO_RHP        619 non-null    int64
 9   AVG_RHP       619 non-null    float64
 10  OBP_RHP       619 non-null    float64
 11  SLG_RHP       619 non-null    float64
 12  Team_y        593 non-null    object
 13  AB_LHP        593 non-null    float64
 14  H_LHP         593 non-null    float64
 15  2B_LHP        593 non-null    float64
 16  3B_LHP        593 non-null    float64
 17  HR_LHP        593 non-null    float64
 18  BB_LHP        593 non-null    float64
 19  SO_LHP        593 non-null    float64
 20  AVG_LHP       593 non-null    float64
 21  OBP_LHP       593 non-null    float64
 22  SLG_LHP       593 non-null    float64
 23  BBE           522 non-null    object
 24  GB%           522 non-null    float64
 25  AIR%          522 non-null    float64
 26  FB%           522 non-null    float64
 27  LD%           522 non-null    float64
 28  PU%           522 non-null    float64
 29  Pull%         522 non-null    float64
 30  Straight%     522 non-null    float64
 31  Oppo%         522 non-null    float64
 32  PullGB%       522 non-null    float64
 33  StraightGB%   522 non-null    float64
 34  OppoGB%       522 non-null    float64
 35  PullAIR%      522 non-null    float64
 36  StraightAIR%  522 non-null    float64
 37  OppoAIR%      522 non-null    float64
 38  PA            602 non-null    object
dtypes: float64(27), int64(7), object(5)
memory usage: 188.7+ KB

### Clean Merged Dataframe

In [31]:
# Replace NaN with column average for columns with percent symbol
for col in master_hitting_stats_df.columns:
    if col.endswith("%"):
        master_hitting_stats_df[col] = master_hitting_stats_df[col].fillna(master_hitting_stats_df[col].mean().round(3))

# Print dataframe sample
master_hitting_stats_df.sample(5)

,Player,Team_x,AB_RHP,H_RHP,2B_RHP,3B_RHP,HR_RHP,BB_RHP,SO_RHP,AVG_RHP,...,Pull%,Straight%,Oppo%,PullGB%,StraightGB%,OppoGB%,PullAIR%,StraightAIR%,OppoAIR%,PA
229,Adam Frazier,PIT,181,49,8,0,3,13,28,0.271,...,0.317,0.359,0.323,0.168,0.162,0.060,0.150,0.198,0.263,222
369,Luis Matos,SF,33,7,1,0,1,3,3,0.212,...,0.339,0.565,0.097,0.161,0.290,0.032,0.177,0.274,0.065,76
241,Marcelo Mayer,BOS,43,10,3,0,3,4,14,0.233,...,0.400,0.314,0.286,0.257,0.200,0.086,0.143,0.114,0.200,58
116,Randy Arozarena,SEA,176,36,9,0,6,32,63,0.205,...,0.387,0.375,0.238,0.161,0.196,0.048,0.226,0.179,0.190,301
432,Jonah Bride,MIN,52,7,1,0,0,3,19,0.135,...,0.324,0.353,0.324,0.162,0.235,0.088,0.162,0.118,0.235,69

In [32]:
# Replace remaining NaN with 0
for col in master_hitting_stats_df.columns:
      master_hitting_stats_df[col] = master_hitting_stats_df[col].fillna(0)

In [33]:
# Drop uneccesary column
master_hitting_stats_df.drop("Team_y", axis=1, inplace=True)

In [35]:
# Rename column
master_hitting_stats_df = master_hitting_stats_df.rename(columns={'Team_x': 'Team'})

In [34]:
# Convert relevant columns to numeric (will force non-numeric values to NaN if they exist)
numeric_columns = master_hitting_stats_df.columns[2:]
master_hitting_stats_df[numeric_columns] = master_hitting_stats_df[numeric_columns].apply(pd.to_numeric, errors='coerce')

In [44]:
# Print dataframe
master_hitting_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 619 entries, 0 to 618
Data columns (total 38 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Player        619 non-null    object
 1   Team          619 non-null    object
 2   AB_RHP        619 non-null    int64
 3   H_RHP         619 non-null    int64
 4   2B_RHP        619 non-null    int64
 5   3B_RHP        619 non-null    int64
 6   HR_RHP        619 non-null    int64
 7   BB_RHP        619 non-null    int64
 8   SO_RHP        619 non-null    int64
 9   AVG_RHP       619 non-null    float64
 10  OBP_RHP       619 non-null    float64
 11  SLG_RHP       619 non-null    float64
 12  AB_LHP        619 non-null    float64
 13  H_LHP         619 non-null    float64
 14  2B_LHP        619 non-null    float64
 15  3B_LHP        619 non-null    float64
 16  HR_LHP        619 non-null    float64
 17  BB_LHP        619 non-null    float64
 18  SO_LHP        619 non-null    float64
 19  AVG_LHP       619 non-null    float64
 20  OBP_LHP       619 non-null    float64
 21  SLG_LHP       619 non-null    float64
 22  BBE           619 non-null    int64
 23  GB%           619 non-null    float64
 24  AIR%          619 non-null    float64
 25  FB%           619 non-null    float64
 26  LD%           619 non-null    float64
 27  PU%           619 non-null    float64
 28  Pull%         619 non-null    float64
 29  Straight%     619 non-null    float64
 30  Oppo%         619 non-null    float64
 31  PullGB%       619 non-null    float64
 32  StraightGB%   619 non-null    float64
 33  OppoGB%       619 non-null    float64
 34  PullAIR%      619 non-null    float64
 35  StraightAIR%  619 non-null    float64
 36  OppoAIR%      619 non-null    float64
 37  PA            619 non-null    int64
dtypes: float64(27), int64(9), object(2)
memory usage: 183.9+ KB

## Create Classes

### Player Class

In [36]:
class Player:
    def __init__(self, name,
                 at_bats_rhp, singles_rhp, doubles_rhp, triples_rhp, home_runs_rhp,
                 OBP_rhp, SLG_rhp, strikeouts_rhp, walks_rhp,
                 at_bats_lhp, singles_lhp, doubles_lhp, triples_lhp, home_runs_lhp,
                 OBP_lhp, SLG_lhp, strikeouts_lhp, walks_lhp,
                 pull_oppo_GB_pct, middle_GB_pct):

        self.name = name

        # vs RHP
        self.at_bats_rhp = at_bats_rhp
        self.singles_rhp = singles_rhp
        self.doubles_rhp = doubles_rhp
        self.triples_rhp = triples_rhp
        self.home_runs_rhp = home_runs_rhp
        self.OBP_rhp = OBP_rhp
        self.SLG_rhp = SLG_rhp
        self.strikeouts_rhp = strikeouts_rhp
        self.walks_rhp = walks_rhp

        # vs LHP
        self.at_bats_lhp = at_bats_lhp
        self.singles_lhp = singles_lhp
        self.doubles_lhp = doubles_lhp
        self.triples_lhp = triples_lhp
        self.home_runs_lhp = home_runs_lhp
        self.OBP_lhp = OBP_lhp
        self.SLG_lhp = SLG_lhp
        self.strikeouts_lhp = strikeouts_lhp
        self.walks_lhp = walks_lhp

        # Groundball splits
        self.pull_oppo_GB_pct = pull_oppo_GB_pct
        self.middle_GB_pct = middle_GB_pct

    # --- Rate Calculations ---
    def find_single_rate(self, vs='rhp'):
        ab = self.at_bats_rhp if vs == 'rhp' else self.at_bats_lhp
        singles = self.singles_rhp if vs == 'rhp' else self.singles_lhp
        return round(singles / ab, 3) if ab > 0 else 0

    def find_double_rate(self, vs='rhp'):
        ab = self.at_bats_rhp if vs == 'rhp' else self.at_bats_lhp
        doubles = self.doubles_rhp if vs == 'rhp' else self.doubles_lhp
        return round(doubles / ab, 3) if ab > 0 else 0

    def find_triple_rate(self, vs='rhp'):
        ab = self.at_bats_rhp if vs == 'rhp' else self.at_bats_lhp
        triples = self.triples_rhp if vs == 'rhp' else self.triples_lhp
        return round(triples / ab, 3) if ab > 0 else 0

    def find_HR_rate(self, vs='rhp'):
        ab = self.at_bats_rhp if vs == 'rhp' else self.at_bats_lhp
        hr = self.home_runs_rhp if vs == 'rhp' else self.home_runs_lhp
        return round(hr / ab, 3) if ab > 0 else 0

    def find_walk_rate(self, vs='rhp'):
        ab = self.at_bats_rhp if vs == 'rhp' else self.at_bats_lhp
        walks = self.walks_rhp if vs == 'rhp' else self.walks_lhp
        return round(walks / ab, 3) if ab > 0 else 0

    # --- Display ---
    def __str__(self):
        return (f"Player: {self.name}\n"
                f"--- vs RHP ---\n"
                f"AB: {self.at_bats_rhp}, BB: {self.walks_rhp}, K: {self.strikeouts_rhp}\n"
                f"1B: {self.singles_rhp}, 2B: {self.doubles_rhp}, 3B: {self.triples_rhp}, HR: {self.home_runs_rhp}\n"
                f"OBP: {self.OBP_rhp}, SLG: {self.SLG_rhp}\n"
                f"--- vs LHP ---\n"
                f"AB: {self.at_bats_lhp}, BB: {self.walks_lhp}, K: {self.strikeouts_lhp}\n"
                f"1B: {self.singles_lhp}, 2B: {self.doubles_lhp}, 3B: {self.triples_lhp}, HR: {self.home_runs_lhp}\n"
                f"OBP: {self.OBP_lhp}, SLG: {self.SLG_lhp}\n"
                f"Groundball Pct (Pull/Oppo): {self.pull_oppo_GB_pct}, Middle: {self.middle_GB_pct}")

    def print_player(self):
        return (f"->   {self.name}      ABs: {(self.at_bats_lhp + self.at_bats_rhp)}")

### BaseRunners Class

In [37]:
# Create BaseRunners class
class BaseRunners:
    def __init__(self):
        # [First base, Second base, Third base]
        self.bases = [None, None, None]
        self.next_runner_id = 1  # simple ID to track runners

    def add_runner(self):
        """Adds a new batter to first base."""
        self.advance_runners(1)

    def advance_runners(self, bases_to_advance):
        """Advances all runners the given number of bases."""
        new_bases = [None, None, None]
        runs = 0

        for i in reversed(range(3)):
            runner = self.bases[i]
            if runner is not None:
                new_position = i + bases_to_advance
                if new_position >= 3:
                    runs += 1  # runner scores
                else:
                    new_bases[new_position] = runner

        # Add the new batter (as a new runner) to first base
        if bases_to_advance >= 4:
            runs += 1
        elif bases_to_advance > 0:
            new_bases[bases_to_advance - 1] = self.next_runner_id
            self.next_runner_id += 1

        self.bases = new_bases
        return runs

    def reset_bases(self):
      """Resets the bases"""
      self.bases = [None, None, None]

    def __str__(self):
        return f"1B: {self.bases[0]}, 2B: {self.bases[1]}, 3B: {self.bases[2]}"

    def is_runner_on_first(self):
        return self.bases[0] is not None

    def is_runner_on_second(self):
      return self.bases[1] is not None

##Testing and Simulation

In [38]:
#Tessst
master_hitting_stats_df[["Player", "AB_RHP", "AB_LHP"]]

             Player  AB_RHP  AB_LHP
0     Shohei Ohtani     183   100.0
1       Cal Raleigh     178    81.0
2    Eugenio Suárez     199    59.0
3    Corbin Carroll     199    82.0
4       Aaron Judge     209    56.0
..              ...     ...     ...
614    Gage Workman      15     1.0
615    Gage Workman      15     1.0
616    Gage Workman      15     1.0
617      Cole Young      36     9.0
618     Jacob Young      92    29.0

[619 rows x 3 columns]

### Set Phillies Lineup

In [45]:
"""Returns a list of players from a team as Player objects"""
def get_players(team):

  players = master_hitting_stats_df[master_hitting_stats_df['Team'] == team]   # Get all players from given team


  players_list = []   # Create list for players

  # Create a player object for each player
  for index, row in players.iterrows():
    player = Player(row['Player'], row['AB_RHP'], (row['H_RHP'] - row['2B_RHP'] - row['3B_RHP'] - row['HR_RHP']),
                    row['2B_RHP'], row['3B_RHP'], row['HR_RHP'], row['OBP_RHP'], row['SLG_RHP'], row['SO_RHP'], row['BB_RHP'],
                    row['AB_LHP'], (row['H_LHP'] - row['2B_LHP'] - row['3B_LHP'] - row['HR_LHP']), row['2B_LHP'], row['3B_LHP'], row['HR_LHP'],
                    row['OBP_LHP'], row['SLG_LHP'], row['SO_LHP'], row['BB_LHP'],
                    round((row['PullGB%'] + row['OppoGB%']), 3), row["StraightGB%"])

    players_list.append(player) # Add player to list

  return players_list

In [46]:
# Print the players in the list
players_list = get_players("PHI")

index = 0
for p in players_list:
  print(f"{p.print_player()}      Index: {index}")
  index += 1

->   Kyle Schwarber      ABs: 262.0      Index: 0
->   Max Kepler      ABs: 213.0      Index: 1
->   Nick Castellanos      ABs: 273.0      Index: 2
->   Alec Bohm      ABs: 270.0      Index: 3
->   J.T. Realmuto      ABs: 219.0      Index: 4
->   Trea Turner      ABs: 288.0      Index: 5
->   Bryce Harper      ABs: 213.0      Index: 6
->   Bryson Stott      ABs: 246.0      Index: 7
->   Rafael Marchán      ABs: 46.0      Index: 8
->   Brandon Marsh      ABs: 129.0      Index: 9
->   Weston Wilson      ABs: 36.0      Index: 10
->   Otto Kemp      ABs: 33.0      Index: 11
->   Johan Rojas      ABs: 114.0      Index: 12
->   Edmundo Sosa      ABs: 95.0      Index: 13
->   Cal Stevenson      ABs: 8.0      Index: 14

In [47]:
# Create list for starting lineup
starting_lineup = []

# Set lineup based on indexes from above code block
starting_lineup.extend([players_list[7], players_list[0], players_list[5],
                                players_list[4], players_list[2], players_list[3],
                                players_list[6], players_list[9], players_list[12]])

### Attempt Basic Simulation

In [48]:
"""Simulates a game against an average RHP"""
def right_hander_sim(innings, batting_order_start_spot):
  spot_in_batting_order = batting_order_start_spot
  total_runs_scored = 0

  # Initialize BaseRunners
  bases = BaseRunners()
  bases.next_runner_id = spot_in_batting_order
  # Simulate Nine Innings
  for num_inning in range(1, innings + 1):
      num_outs = 0
      runs_scored = 0
      bases.reset_bases()
      print(f"\n--------------- Inning {num_inning} ---------------")
  # Simulate One Inning
      while num_outs < 3:
        player_at_bat = starting_lineup[spot_in_batting_order - 1]
        random_number = round(random.uniform(0, 1), 3)
        print(f"\n{player_at_bat.name} - {random_number}")
        """Check for Hit, Out, or Other Event"""
        if random_number > player_at_bat.OBP_rhp: # Got out
          # Out logic
          strikeout_chance = player_at_bat.strikeouts_rhp / player_at_bat.at_bats_rhp
          groundout_chance = (1 - player_at_bat.OBP_rhp) * (player_at_bat.pull_oppo_GB_pct + player_at_bat.middle_GB_pct)
          airout_chance = (1 - player_at_bat.OBP_rhp) * (1 - (player_at_bat.pull_oppo_GB_pct + player_at_bat.middle_GB_pct))

          if random_number < (player_at_bat.OBP_rhp + strikeout_chance): # Strikout
              num_outs += 1
              print(f"---- Strikeout - {num_outs} Outs ----")
          elif random_number < (player_at_bat.OBP_rhp + strikeout_chance + groundout_chance): # Groundout
              random_num = round(random.uniform(0, (player_at_bat.pull_oppo_GB_pct + player_at_bat.middle_GB_pct)), 3)
              if (random_num < player_at_bat.pull_oppo_GB_pct) & (bases.is_runner_on_first() == True) & (num_outs <= 1):
                num_outs += 2
                print(f"---- Double Play - {num_outs} Outs ----")
              else:
                num_outs += 1
                print(f"---- Groundout - {num_outs} Outs ----")
          else: # Flyout
              num_outs += 1
              print(f"---- Flyout - {num_outs} Outs ----")

        else: # Got on base
          single_rate = player_at_bat.find_single_rate(vs='rhp')
          double_rate = player_at_bat.find_double_rate(vs='rhp')
          triple_rate = player_at_bat.find_triple_rate(vs='rhp')
          HR_rate = player_at_bat.find_HR_rate(vs='rhp')
          walk_rate = player_at_bat.find_walk_rate(vs='rhp')

          """ Check what type of hit player got """
          if random_number < (walk_rate):
            runs_batted_in = bases.advance_runners(1)
            print("Walk!")
          elif random_number < (walk_rate + single_rate):
            runs_batted_in = bases.advance_runners(1)
            print("Single!")
          elif random_number < (walk_rate + single_rate + double_rate):
            runs_batted_in = bases.advance_runners(2)
            print("Double!")
          elif random_number < (walk_rate + single_rate + double_rate + triple_rate):
            runs_batted_in = bases.advance_runners(3)
            print("Triple!")
          elif random_number < (walk_rate + single_rate + double_rate + triple_rate + HR_rate):
            runs_batted_in = bases.advance_runners(4)
            print("Home Run!")
          else: # Need to make checks more precise, this else statement is just a placeholder
            runs_batted_in = bases.advance_runners(1)
            print("Error/Fielder's Choice!")

          print(f"{player_at_bat.name} hit in {runs_batted_in} runs")
          print(f"Bases - {bases}")
          runs_scored += runs_batted_in   # Calculate runs scored in the inning
          total_runs_scored += runs_batted_in  # Calculate runs scored in the game
        spot_in_batting_order += 1
        if spot_in_batting_order > 9:
          spot_in_batting_order = 1

      # Print runs for inning
      print(f"\nRuns Scored in Inning: {runs_scored}")
      print(f"Runs Scored in Game: {total_runs_scored}\n")

  return total_runs_scored

In [49]:
"""Simulates a game against an average LHP"""
def left_hander_sim(innings, batting_order_start_spot):
  spot_in_batting_order = batting_order_start_spot
  total_runs_scored = 0

  # Initialize BaseRunners
  bases = BaseRunners()
  bases.next_runner_id = spot_in_batting_order
  # Simulate Nine Innings
  for num_inning in range(1, innings + 1):
      num_outs = 0
      runs_scored = 0
      bases.reset_bases()
      print(f"\n--------------- Inning {num_inning} ---------------")
  # Simulate One Inning
      while num_outs < 3:
        player_at_bat = starting_lineup[spot_in_batting_order - 1]
        random_number = round(random.uniform(0, 1), 3)
        print(f"\n{player_at_bat.name} - {random_number}")
        """Check for Hit, Out, or Other Event"""
        if random_number > player_at_bat.OBP_lhp: # Got out
          # Out logic
          strikeout_chance = player_at_bat.strikeouts_lhp / player_at_bat.at_bats_lhp
          groundout_chance = (1 - player_at_bat.OBP_lhp) * (player_at_bat.pull_oppo_GB_pct + player_at_bat.middle_GB_pct)
          airout_chance = (1 - player_at_bat.OBP_lhp) * (1 - (player_at_bat.pull_oppo_GB_pct + player_at_bat.middle_GB_pct))

          if random_number < (player_at_bat.OBP_lhp + strikeout_chance): # Strikeout
              num_outs += 1
              print(f"---- Strikeout - {num_outs} Outs ----")
          elif random_number < (player_at_bat.OBP_lhp + strikeout_chance + groundout_chance): # Groundout
              random_num = round(random.uniform(0, (player_at_bat.pull_oppo_GB_pct + player_at_bat.middle_GB_pct)), 3)
              if (random_num < player_at_bat.pull_oppo_GB_pct) & (bases.is_runner_on_first() == True) & (num_outs <= 1):
                num_outs += 2
                print(f"---- Double Play - {num_outs} Outs ----")
              else:
                num_outs += 1
                print(f"---- Groundout - {num_outs} Outs ----")
          else: # Flyout
              num_outs += 1
              print(f"---- Flyout - {num_outs} Outs ----")

        else: # Got on base
          single_rate = player_at_bat.find_single_rate()
          double_rate = player_at_bat.find_double_rate()
          triple_rate = player_at_bat.find_triple_rate()
          HR_rate = player_at_bat.find_HR_rate()
          walk_rate = player_at_bat.find_walk_rate()

          """ Check what type of hit player got """
          if random_number < (walk_rate):
            runs_batted_in = bases.advance_runners(1)
            print("Walk!")
          elif random_number < (walk_rate + single_rate):
            runs_batted_in = bases.advance_runners(1)
            print("Single!")
          elif random_number < (walk_rate + single_rate + double_rate):
            runs_batted_in = bases.advance_runners(2)
            print("Double!")
          elif random_number < (walk_rate + single_rate + double_rate + triple_rate):
            runs_batted_in = bases.advance_runners(3)
            print("Triple!")
          elif random_number < (walk_rate + single_rate + double_rate + triple_rate + HR_rate):
            runs_batted_in = bases.advance_runners(4)
            print("Home Run!")
          else: # Need to make checks more precise, this else statement is just a placeholder
            runs_batted_in = bases.advance_runners(1)
            print("Error/Fielder's Choice!")

          print(f"{player_at_bat.name} hit in {runs_batted_in} runs")
          print(f"Bases - {bases}")
          runs_scored += runs_batted_in   # Calculate runs scored in the inning
          total_runs_scored += runs_batted_in  # Calculate runs scored in the game
        spot_in_batting_order += 1
        if spot_in_batting_order > 9:
          spot_in_batting_order = 1

      # Print runs for inning
      print(f"\nRuns Scored in Inning: {runs_scored}")
      print(f"Runs Scored in Game: {total_runs_scored}\n")

  return total_runs_scored

In [52]:
# Simulate vs right handed pitcher
total_sum = 0
for i in range(0, 999):
  total_sum += right_hander_sim(9, 1)

print(f"Average Runs Scored: {total_sum / 1000}")

Streaming output truncated to the last 5000 lines.
Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 6 ---------------

Nick Castellanos - 0.492
---- Strikeout - 1 Outs ----

Alec Bohm - 0.799
---- Groundout - 2 Outs ----

Bryce Harper - 0.291
Single!
Bryce Harper hit in 0 runs
Bases - 1B: 9, 2B: None, 3B: None

Brandon Marsh - 0.287
Single!
Brandon Marsh hit in 0 runs
Bases - 1B: 10, 2B: 9, 3B: None

Johan Rojas - 0.842
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 7 ---------------

Bryson Stott - 0.932
---- Flyout - 1 Outs ----

Kyle Schwarber - 0.254
Single!
Kyle Schwarber hit in 0 runs
Bases - 1B: 11, 2B: None, 3B: None

Trea Turner - 0.617
---- Groundout - 2 Outs ----

J.T. Realmuto - 0.516
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 8 ---------------

Nick Castellanos - 0.243
Double!
Nick Castellanos hit in 0 runs
Bases - 1B: None, 2B: 12, 3B: None

Alec Bohm - 0.351
---- Strikeout - 1 Outs ----

Bryce Harper - 0.979
---- Flyout - 2 Outs ----

Brandon Marsh - 0.79
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 9 ---------------

Johan Rojas - 0.609
---- Strikeout - 1 Outs ----

Bryson Stott - 0.117
Single!
Bryson Stott hit in 0 runs
Bases - 1B: 13, 2B: None, 3B: None

Kyle Schwarber - 0.097
Walk!
Kyle Schwarber hit in 0 runs
Bases - 1B: 14, 2B: 13, 3B: None

Trea Turner - 0.676
---- Double Play - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 1 ---------------

Bryson Stott - 0.143
Single!
Bryson Stott hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

Kyle Schwarber - 0.947
---- Flyout - 1 Outs ----

Trea Turner - 0.666
---- Double Play - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

J.T. Realmuto - 0.532
---- Strikeout - 1 Outs ----

Nick Castellanos - 0.573
---- Groundout - 2 Outs ----

Alec Bohm - 0.811
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Bryce Harper - 0.486
---- Strikeout - 1 Outs ----

Brandon Marsh - 0.813
---- Groundout - 2 Outs ----

Johan Rojas - 0.053
Walk!
Johan Rojas hit in 0 runs
Bases - 1B: 2, 2B: None, 3B: None

Bryson Stott - 0.762
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 4 ---------------

Kyle Schwarber - 0.812
---- Groundout - 1 Outs ----

Trea Turner - 0.339
Double!
Trea Turner hit in 0 runs
Bases - 1B: None, 2B: 3, 3B: None

J.T. Realmuto - 0.757
---- Groundout - 2 Outs ----

Nick Castellanos - 0.905
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 5 ---------------

Alec Bohm - 0.838
---- Flyout - 1 Outs ----

Bryce Harper - 0.188
Walk!
Bryce Harper hit in 0 runs
Bases - 1B: 4, 2B: None, 3B: None

Brandon Marsh - 0.082
Walk!
Brandon Marsh hit in 0 runs
Bases - 1B: 5, 2B: 4, 3B: None

Johan Rojas - 0.499
---- Strikeout - 2 Outs ----

Bryson Stott - 0.156
Single!
Bryson Stott hit in 0 runs
Bases - 1B: 6, 2B: 5, 3B: 4

Kyle Schwarber - 0.376
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 6 ---------------

Trea Turner - 0.572
---- Groundout - 1 Outs ----

J.T. Realmuto - 0.975
---- Flyout - 2 Outs ----

Nick Castellanos - 0.354
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 7 ---------------

Alec Bohm - 0.972
---- Flyout - 1 Outs ----

Bryce Harper - 0.471
---- Strikeout - 2 Outs ----

Brandon Marsh - 0.994
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 8 ---------------

Johan Rojas - 0.735
---- Groundout - 1 Outs ----

Bryson Stott - 0.657
---- Groundout - 2 Outs ----

Kyle Schwarber - 0.922
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 9 ---------------

Trea Turner - 0.506
---- Strikeout - 1 Outs ----

J.T. Realmuto - 0.924
---- Groundout - 2 Outs ----

Nick Castellanos - 0.447
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 1 ---------------

Bryson Stott - 0.667
---- Groundout - 1 Outs ----

Kyle Schwarber - 0.785
---- Groundout - 2 Outs ----

Trea Turner - 0.146
Single!
Trea Turner hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

J.T. Realmuto - 0.088
Walk!
J.T. Realmuto hit in 0 runs
Bases - 1B: 2, 2B: 1, 3B: None

Nick Castellanos - 0.434
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

Alec Bohm - 0.345
---- Strikeout - 1 Outs ----

Bryce Harper - 0.874
---- Flyout - 2 Outs ----

Brandon Marsh - 0.266
Single!
Brandon Marsh hit in 0 runs
Bases - 1B: 3, 2B: None, 3B: None

Johan Rojas - 0.947
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Bryson Stott - 0.076
Walk!
Bryson Stott hit in 0 runs
Bases - 1B: 4, 2B: None, 3B: None

Kyle Schwarber - 0.592
---- Strikeout - 1 Outs ----

Trea Turner - 0.866
---- Flyout - 2 Outs ----

J.T. Realmuto - 0.448
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 4 ---------------

Nick Castellanos - 0.603
---- Groundout - 1 Outs ----

Alec Bohm - 0.904
---- Flyout - 2 Outs ----

Bryce Harper - 0.504
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 5 ---------------

Brandon Marsh - 0.82
---- Groundout - 1 Outs ----

Johan Rojas - 0.681
---- Groundout - 2 Outs ----

Bryson Stott - 0.881
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 6 ---------------

Kyle Schwarber - 0.594
---- Strikeout - 1 Outs ----

Trea Turner - 0.084
Walk!
Trea Turner hit in 0 runs
Bases - 1B: 5, 2B: None, 3B: None

J.T. Realmuto - 0.991
---- Flyout - 2 Outs ----

Nick Castellanos - 0.121
Single!
Nick Castellanos hit in 0 runs
Bases - 1B: 6, 2B: 5, 3B: None

Alec Bohm - 0.117
Single!
Alec Bohm hit in 0 runs
Bases - 1B: 7, 2B: 6, 3B: 5

Bryce Harper - 0.765
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 7 ---------------

Brandon Marsh - 0.534
---- Strikeout - 1 Outs ----

Johan Rojas - 0.657
---- Groundout - 2 Outs ----

Bryson Stott - 0.264
Double!
Bryson Stott hit in 0 runs
Bases - 1B: None, 2B: 8, 3B: None

Kyle Schwarber - 0.241
Single!
Kyle Schwarber hit in 0 runs
Bases - 1B: 9, 2B: None, 3B: 8

Trea Turner - 0.72
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 8 ---------------

J.T. Realmuto - 0.195
Single!
J.T. Realmuto hit in 0 runs
Bases - 1B: 10, 2B: None, 3B: None

Nick Castellanos - 0.334
---- Strikeout - 1 Outs ----

Alec Bohm - 0.923
---- Flyout - 2 Outs ----

Bryce Harper - 0.121
Walk!
Bryce Harper hit in 0 runs
Bases - 1B: 11, 2B: 10, 3B: None

Brandon Marsh - 0.911
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 9 ---------------

Johan Rojas - 0.145
Single!
Johan Rojas hit in 0 runs
Bases - 1B: 12, 2B: None, 3B: None

Bryson Stott - 0.695
---- Groundout - 1 Outs ----

Kyle Schwarber - 0.247
Single!
Kyle Schwarber hit in 0 runs
Bases - 1B: 13, 2B: 12, 3B: None

Trea Turner - 0.249
Single!
Trea Turner hit in 0 runs
Bases - 1B: 14, 2B: 13, 3B: 12

J.T. Realmuto - 0.677
---- Double Play - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 1 ---------------

Bryson Stott - 0.518
---- Groundout - 1 Outs ----

Kyle Schwarber - 0.941
---- Flyout - 2 Outs ----

Trea Turner - 0.391
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

J.T. Realmuto - 0.438
---- Strikeout - 1 Outs ----

Nick Castellanos - 0.871
---- Flyout - 2 Outs ----

Alec Bohm - 0.717
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Bryce Harper - 0.938
---- Flyout - 1 Outs ----

Brandon Marsh - 0.451
---- Strikeout - 2 Outs ----

Johan Rojas - 0.293
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 4 ---------------

Bryson Stott - 0.047
Walk!
Bryson Stott hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

Kyle Schwarber - 0.036
Walk!
Kyle Schwarber hit in 0 runs
Bases - 1B: 2, 2B: 1, 3B: None

Trea Turner - 0.331
Double!
Trea Turner hit in 1 runs
Bases - 1B: None, 2B: 3, 3B: 2

J.T. Realmuto - 0.702
---- Groundout - 1 Outs ----

Nick Castellanos - 0.019
Walk!
Nick Castellanos hit in 1 runs
Bases - 1B: 4, 2B: None, 3B: 3

Alec Bohm - 0.05
Walk!
Alec Bohm hit in 1 runs
Bases - 1B: 5, 2B: 4, 3B: None

Bryce Harper - 0.008
Walk!
Bryce Harper hit in 0 runs
Bases - 1B: 6, 2B: 5, 3B: 4

Brandon Marsh - 0.76
---- Double Play - 3 Outs ----

Runs Scored in Inning: 3
Runs Scored in Game: 3


--------------- Inning 5 ---------------

Johan Rojas - 0.524
---- Strikeout - 1 Outs ----

Bryson Stott - 0.589
---- Groundout - 2 Outs ----

Kyle Schwarber - 0.593
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 3


--------------- Inning 6 ---------------

Trea Turner - 0.197
Single!
Trea Turner hit in 0 runs
Bases - 1B: 7, 2B: None, 3B: None

J.T. Realmuto - 0.361
Triple!
J.T. Realmuto hit in 1 runs
Bases - 1B: None, 2B: None, 3B: 8

Nick Castellanos - 0.454
---- Strikeout - 1 Outs ----

Alec Bohm - 0.675
---- Groundout - 2 Outs ----

Bryce Harper - 0.666
---- Groundout - 3 Outs ----

Runs Scored in Inning: 1
Runs Scored in Game: 4


--------------- Inning 7 ---------------

Brandon Marsh - 0.489
---- Strikeout - 1 Outs ----

Johan Rojas - 0.679
---- Groundout - 2 Outs ----

Bryson Stott - 0.224
Single!
Bryson Stott hit in 0 runs
Bases - 1B: 9, 2B: None, 3B: None

Kyle Schwarber - 0.595
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 4


--------------- Inning 8 ---------------

Trea Turner - 0.581
---- Groundout - 1 Outs ----

J.T. Realmuto - 0.093
Walk!
J.T. Realmuto hit in 0 runs
Bases - 1B: 10, 2B: None, 3B: None

Nick Castellanos - 0.305
---- Strikeout - 2 Outs ----

Alec Bohm - 0.463
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 4


--------------- Inning 9 ---------------

Bryce Harper - 0.18
Walk!
Bryce Harper hit in 0 runs
Bases - 1B: 11, 2B: None, 3B: None

Brandon Marsh - 0.842
---- Double Play - 2 Outs ----

Johan Rojas - 0.642
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 4


--------------- Inning 1 ---------------

Bryson Stott - 0.086
Walk!
Bryson Stott hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

Kyle Schwarber - 0.74
---- Groundout - 1 Outs ----

Trea Turner - 0.553
---- Strikeout - 2 Outs ----

J.T. Realmuto - 0.898
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

Nick Castellanos - 0.967
---- Flyout - 1 Outs ----

Alec Bohm - 0.708
---- Groundout - 2 Outs ----

Bryce Harper - 0.27
Single!
Bryce Harper hit in 0 runs
Bases - 1B: 2, 2B: None, 3B: None

Brandon Marsh - 0.771
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Johan Rojas - 0.131
Single!
Johan Rojas hit in 0 runs
Bases - 1B: 3, 2B: None, 3B: None

Bryson Stott - 0.317
---- Strikeout - 1 Outs ----

Kyle Schwarber - 0.647
---- Strikeout - 2 Outs ----

Trea Turner - 0.306
Single!
Trea Turner hit in 0 runs
Bases - 1B: 4, 2B: 3, 3B: None

J.T. Realmuto - 0.295
Single!
J.T. Realmuto hit in 0 runs
Bases - 1B: 5, 2B: 4, 3B: 3

Nick Castellanos - 0.239
Double!
Nick Castellanos hit in 2 runs
Bases - 1B: None, 2B: 6, 3B: 5

Alec Bohm - 0.431
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 2
Runs Scored in Game: 2


--------------- Inning 4 ---------------

Bryce Harper - 0.585
---- Strikeout - 1 Outs ----

Brandon Marsh - 0.588
---- Strikeout - 2 Outs ----

Johan Rojas - 0.394
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 2


--------------- Inning 5 ---------------

Bryson Stott - 0.869
---- Flyout - 1 Outs ----

Kyle Schwarber - 0.747
---- Groundout - 2 Outs ----

Trea Turner - 0.254
Single!
Trea Turner hit in 0 runs
Bases - 1B: 7, 2B: None, 3B: None

J.T. Realmuto - 0.164
Single!
J.T. Realmuto hit in 0 runs
Bases - 1B: 8, 2B: 7, 3B: None

Nick Castellanos - 0.404
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 2


--------------- Inning 6 ---------------

Alec Bohm - 0.366
---- Strikeout - 1 Outs ----

Bryce Harper - 0.753
---- Groundout - 2 Outs ----

Brandon Marsh - 0.464
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 2


--------------- Inning 7 ---------------

Johan Rojas - 0.981
---- Groundout - 1 Outs ----

Bryson Stott - 0.328
---- Strikeout - 2 Outs ----

Kyle Schwarber - 0.6
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 2


--------------- Inning 8 ---------------

Trea Turner - 0.607
---- Groundout - 1 Outs ----

J.T. Realmuto - 0.53
---- Strikeout - 2 Outs ----

Nick Castellanos - 0.121
Single!
Nick Castellanos hit in 0 runs
Bases - 1B: 9, 2B: None, 3B: None

Alec Bohm - 0.731
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 2


--------------- Inning 9 ---------------

Bryce Harper - 0.293
Single!
Bryce Harper hit in 0 runs
Bases - 1B: 10, 2B: None, 3B: None

Brandon Marsh - 0.699
---- Double Play - 2 Outs ----

Johan Rojas - 0.4
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 2


--------------- Inning 1 ---------------

Bryson Stott - 0.724
---- Groundout - 1 Outs ----

Kyle Schwarber - 0.118
Walk!
Kyle Schwarber hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

Trea Turner - 0.544
---- Strikeout - 2 Outs ----

J.T. Realmuto - 0.544
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

Nick Castellanos - 0.329
---- Strikeout - 1 Outs ----

Alec Bohm - 0.313
Home Run!
Alec Bohm hit in 1 runs
Bases - 1B: None, 2B: None, 3B: None

Bryce Harper - 0.353
Double!
Bryce Harper hit in 0 runs
Bases - 1B: None, 2B: 2, 3B: None

Brandon Marsh - 0.479
---- Strikeout - 2 Outs ----

Johan Rojas - 0.527
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 1
Runs Scored in Game: 1


--------------- Inning 3 ---------------

Bryson Stott - 0.318
---- Strikeout - 1 Outs ----

Kyle Schwarber - 0.102
Walk!
Kyle Schwarber hit in 0 runs
Bases - 1B: 3, 2B: None, 3B: None

Trea Turner - 0.569
---- Groundout - 2 Outs ----

J.T. Realmuto - 0.175
Single!
J.T. Realmuto hit in 0 runs
Bases - 1B: 4, 2B: 3, 3B: None

Nick Castellanos - 0.181
Single!
Nick Castellanos hit in 0 runs
Bases - 1B: 5, 2B: 4, 3B: 3

Alec Bohm - 0.436
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 4 ---------------

Bryce Harper - 0.322
Single!
Bryce Harper hit in 0 runs
Bases - 1B: 6, 2B: None, 3B: None

Brandon Marsh - 0.278
Single!
Brandon Marsh hit in 0 runs
Bases - 1B: 7, 2B: 6, 3B: None

Johan Rojas - 0.233
Single!
Johan Rojas hit in 0 runs
Bases - 1B: 8, 2B: 7, 3B: 6

Bryson Stott - 0.85
---- Flyout - 1 Outs ----

Kyle Schwarber - 0.413
---- Strikeout - 2 Outs ----

Trea Turner - 0.658
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 5 ---------------

J.T. Realmuto - 0.449
---- Strikeout - 1 Outs ----

Nick Castellanos - 0.784
---- Flyout - 2 Outs ----

Alec Bohm - 0.685
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 6 ---------------

Bryce Harper - 0.577
---- Strikeout - 1 Outs ----

Brandon Marsh - 0.083
Walk!
Brandon Marsh hit in 0 runs
Bases - 1B: 9, 2B: None, 3B: None

Johan Rojas - 0.322
---- Strikeout - 2 Outs ----

Bryson Stott - 0.279
Double!
Bryson Stott hit in 0 runs
Bases - 1B: None, 2B: 10, 3B: 9

Kyle Schwarber - 0.486
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 7 ---------------

Trea Turner - 0.283
Single!
Trea Turner hit in 0 runs
Bases - 1B: 11, 2B: None, 3B: None

J.T. Realmuto - 0.597
---- Strikeout - 1 Outs ----

Nick Castellanos - 0.649
---- Groundout - 2 Outs ----

Alec Bohm - 0.717
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 8 ---------------

Bryce Harper - 0.803
---- Groundout - 1 Outs ----

Brandon Marsh - 0.409
---- Strikeout - 2 Outs ----

Johan Rojas - 0.344
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 9 ---------------

Bryson Stott - 0.065
Walk!
Bryson Stott hit in 0 runs
Bases - 1B: 12, 2B: None, 3B: None

Kyle Schwarber - 0.532
---- Strikeout - 1 Outs ----

Trea Turner - 0.431
---- Strikeout - 2 Outs ----

J.T. Realmuto - 0.307
Double!
J.T. Realmuto hit in 0 runs
Bases - 1B: None, 2B: 13, 3B: 12

Nick Castellanos - 0.362
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 1 ---------------

Bryson Stott - 0.86
---- Flyout - 1 Outs ----

Kyle Schwarber - 0.8
---- Groundout - 2 Outs ----

Trea Turner - 0.616
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

J.T. Realmuto - 0.062
Walk!
J.T. Realmuto hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

Nick Castellanos - 0.797
---- Flyout - 1 Outs ----

Alec Bohm - 0.084
Single!
Alec Bohm hit in 0 runs
Bases - 1B: 2, 2B: 1, 3B: None

Bryce Harper - 0.673
---- Groundout - 2 Outs ----

Brandon Marsh - 0.531
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Johan Rojas - 0.215
Single!
Johan Rojas hit in 0 runs
Bases - 1B: 3, 2B: None, 3B: None

Bryson Stott - 0.199
Single!
Bryson Stott hit in 0 runs
Bases - 1B: 4, 2B: 3, 3B: None

Kyle Schwarber - 0.868
---- Double Play - 2 Outs ----

Trea Turner - 0.214
Single!
Trea Turner hit in 0 runs
Bases - 1B: 5, 2B: 4, 3B: 3

J.T. Realmuto - 0.726
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 4 ---------------

Nick Castellanos - 0.839
---- Flyout - 1 Outs ----

Alec Bohm - 0.671
---- Groundout - 2 Outs ----

Bryce Harper - 0.902
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 5 ---------------

Brandon Marsh - 0.842
---- Groundout - 1 Outs ----

Johan Rojas - 0.643
---- Groundout - 2 Outs ----

Bryson Stott - 0.331
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 6 ---------------

Kyle Schwarber - 0.301
Single!
Kyle Schwarber hit in 0 runs
Bases - 1B: 6, 2B: None, 3B: None

Trea Turner - 0.074
Walk!
Trea Turner hit in 0 runs
Bases - 1B: 7, 2B: 6, 3B: None

J.T. Realmuto - 0.767
---- Groundout - 1 Outs ----

Nick Castellanos - 0.907
---- Flyout - 2 Outs ----

Alec Bohm - 0.783
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 7 ---------------

Bryce Harper - 0.969
---- Flyout - 1 Outs ----

Brandon Marsh - 0.836
---- Groundout - 2 Outs ----

Johan Rojas - 0.008
Walk!
Johan Rojas hit in 0 runs
Bases - 1B: 8, 2B: None, 3B: None

Bryson Stott - 0.384
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 8 ---------------

Kyle Schwarber - 0.46
---- Strikeout - 1 Outs ----

Trea Turner - 0.486
---- Strikeout - 2 Outs ----

J.T. Realmuto - 0.529
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 9 ---------------

Nick Castellanos - 0.847
---- Flyout - 1 Outs ----

Alec Bohm - 0.901

In [51]:
# Simulate vs left handed pitcher
total_sum = 0
for i in range(0, 999):
  total_sum += left_hander_sim(9, 1)

print(f"Average Runs Scored:  {total_sum / 1000}")

Streaming output truncated to the last 5000 lines.
Walk!
Trea Turner hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

J.T. Realmuto - 0.802
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

Nick Castellanos - 0.976
---- Flyout - 1 Outs ----

Alec Bohm - 0.391
---- Strikeout - 2 Outs ----

Bryce Harper - 0.012
Walk!
Bryce Harper hit in 0 runs
Bases - 1B: 2, 2B: None, 3B: None

Brandon Marsh - 0.37
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Johan Rojas - 0.49
---- Strikeout - 1 Outs ----

Bryson Stott - 0.089
Single!
Bryson Stott hit in 0 runs
Bases - 1B: 3, 2B: None, 3B: None

Kyle Schwarber - 0.992
---- Flyout - 2 Outs ----

Trea Turner - 0.236
Single!
Trea Turner hit in 0 runs
Bases - 1B: 4, 2B: 3, 3B: None

J.T. Realmuto - 0.842
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 4 ---------------

Nick Castellanos - 0.643
---- Groundout - 1 Outs ----

Alec Bohm - 0.371
---- Strikeout - 2 Outs ----

Bryce Harper - 0.258
Single!
Bryce Harper hit in 0 runs
Bases - 1B: 5, 2B: None, 3B: None

Brandon Marsh - 0.206
Single!
Brandon Marsh hit in 0 runs
Bases - 1B: 6, 2B: 5, 3B: None

Johan Rojas - 0.887
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 5 ---------------

Bryson Stott - 0.025
Walk!
Bryson Stott hit in 0 runs
Bases - 1B: 7, 2B: None, 3B: None

Kyle Schwarber - 0.858
---- Double Play - 2 Outs ----

Trea Turner - 0.642
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 6 ---------------

J.T. Realmuto - 0.996
---- Flyout - 1 Outs ----

Nick Castellanos - 0.02
Walk!
Nick Castellanos hit in 0 runs
Bases - 1B: 8, 2B: None, 3B: None

Alec Bohm - 0.101
Single!
Alec Bohm hit in 0 runs
Bases - 1B: 9, 2B: 8, 3B: None

Bryce Harper - 0.458
---- Strikeout - 2 Outs ----

Brandon Marsh - 0.375
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 7 ---------------

Johan Rojas - 0.64
---- Groundout - 1 Outs ----

Bryson Stott - 0.796
---- Flyout - 2 Outs ----

Kyle Schwarber - 0.627
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 8 ---------------

Trea Turner - 0.93
---- Flyout - 1 Outs ----

J.T. Realmuto - 0.167
Single!
J.T. Realmuto hit in 0 runs
Bases - 1B: 10, 2B: None, 3B: None

Nick Castellanos - 0.769
---- Double Play - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 9 ---------------

Alec Bohm - 0.644
---- Groundout - 1 Outs ----

Bryce Harper - 0.837
---- Flyout - 2 Outs ----

Brandon Marsh - 0.579
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 1 ---------------

Bryson Stott - 0.372
---- Strikeout - 1 Outs ----

Kyle Schwarber - 0.806
---- Groundout - 2 Outs ----

Trea Turner - 0.125
Single!
Trea Turner hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

J.T. Realmuto - 0.916
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

Nick Castellanos - 0.885
---- Flyout - 1 Outs ----

Alec Bohm - 0.931
---- Flyout - 2 Outs ----

Bryce Harper - 0.98
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Brandon Marsh - 0.443
---- Strikeout - 1 Outs ----

Johan Rojas - 0.527
---- Groundout - 2 Outs ----

Bryson Stott - 0.572
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 4 ---------------

Kyle Schwarber - 0.987
---- Flyout - 1 Outs ----

Trea Turner - 0.512
---- Strikeout - 2 Outs ----

J.T. Realmuto - 0.403
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 5 ---------------

Nick Castellanos - 0.314
Home Run!
Nick Castellanos hit in 1 runs
Bases - 1B: None, 2B: None, 3B: None

Alec Bohm - 0.036
Walk!
Alec Bohm hit in 0 runs
Bases - 1B: 2, 2B: None, 3B: None

Bryce Harper - 0.673
---- Groundout - 1 Outs ----

Brandon Marsh - 0.521
---- Strikeout - 2 Outs ----

Johan Rojas - 0.734
---- Groundout - 3 Outs ----

Runs Scored in Inning: 1
Runs Scored in Game: 1


--------------- Inning 6 ---------------

Bryson Stott - 0.519
---- Strikeout - 1 Outs ----

Kyle Schwarber - 0.53
---- Strikeout - 2 Outs ----

Trea Turner - 0.952
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 7 ---------------

J.T. Realmuto - 0.275
---- Strikeout - 1 Outs ----

Nick Castellanos - 0.17
Single!
Nick Castellanos hit in 0 runs
Bases - 1B: 3, 2B: None, 3B: None

Alec Bohm - 0.911
---- Flyout - 2 Outs ----

Bryce Harper - 0.35
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 8 ---------------

Brandon Marsh - 0.607
---- Strikeout - 1 Outs ----

Johan Rojas - 0.566
---- Groundout - 2 Outs ----

Bryson Stott - 0.606
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 9 ---------------

Kyle Schwarber - 0.12
Walk!
Kyle Schwarber hit in 0 runs
Bases - 1B: 4, 2B: None, 3B: None

Trea Turner - 0.786
---- Double Play - 2 Outs ----

J.T. Realmuto - 0.101
Walk!
J.T. Realmuto hit in 0 runs
Bases - 1B: 5, 2B: 4, 3B: None

Nick Castellanos - 0.134
Single!
Nick Castellanos hit in 0 runs
Bases - 1B: 6, 2B: 5, 3B: 4

Alec Bohm - 0.101
Single!
Alec Bohm hit in 1 runs
Bases - 1B: 7, 2B: 6, 3B: 5

Bryce Harper - 0.717
---- Groundout - 3 Outs ----

Runs Scored in Inning: 1
Runs Scored in Game: 2


--------------- Inning 1 ---------------

Bryson Stott - 0.084
Walk!
Bryson Stott hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

Kyle Schwarber - 0.883
---- Groundout - 1 Outs ----

Trea Turner - 0.268
Single!
Trea Turner hit in 0 runs
Bases - 1B: 2, 2B: 1, 3B: None

J.T. Realmuto - 0.57
---- Double Play - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

Nick Castellanos - 0.822
---- Flyout - 1 Outs ----

Alec Bohm - 0.326
---- Strikeout - 2 Outs ----

Bryce Harper - 0.883
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Brandon Marsh - 0.815
---- Strikeout - 1 Outs ----

Johan Rojas - 0.746
---- Groundout - 2 Outs ----

Bryson Stott - 0.383
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 4 ---------------

Kyle Schwarber - 0.05
Walk!
Kyle Schwarber hit in 0 runs
Bases - 1B: 3, 2B: None, 3B: None

Trea Turner - 0.208
Single!
Trea Turner hit in 0 runs
Bases - 1B: 4, 2B: 3, 3B: None

J.T. Realmuto - 0.013
Walk!
J.T. Realmuto hit in 0 runs
Bases - 1B: 5, 2B: 4, 3B: 3

Nick Castellanos - 0.03
Walk!
Nick Castellanos hit in 1 runs
Bases - 1B: 6, 2B: 5, 3B: 4

Alec Bohm - 0.537
---- Groundout - 1 Outs ----

Bryce Harper - 0.67
---- Double Play - 3 Outs ----

Runs Scored in Inning: 1
Runs Scored in Game: 1


--------------- Inning 5 ---------------

Brandon Marsh - 0.059
Walk!
Brandon Marsh hit in 0 runs
Bases - 1B: 7, 2B: None, 3B: None

Johan Rojas - 0.086
Walk!
Johan Rojas hit in 0 runs
Bases - 1B: 8, 2B: 7, 3B: None

Bryson Stott - 0.623
---- Groundout - 1 Outs ----

Kyle Schwarber - 0.031
Walk!
Kyle Schwarber hit in 0 runs
Bases - 1B: 9, 2B: 8, 3B: 7

Trea Turner - 0.524
---- Double Play - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 6 ---------------

J.T. Realmuto - 0.946
---- Flyout - 1 Outs ----

Nick Castellanos - 0.473
---- Strikeout - 2 Outs ----

Alec Bohm - 0.389
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 7 ---------------

Bryce Harper - 0.544
---- Strikeout - 1 Outs ----

Brandon Marsh - 0.377
---- Strikeout - 2 Outs ----

Johan Rojas - 0.698
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 8 ---------------

Bryson Stott - 0.168
Single!
Bryson Stott hit in 0 runs
Bases - 1B: 10, 2B: None, 3B: None

Kyle Schwarber - 0.174
Walk!
Kyle Schwarber hit in 0 runs
Bases - 1B: 11, 2B: 10, 3B: None

Trea Turner - 0.809
---- Flyout - 1 Outs ----

J.T. Realmuto - 0.51
---- Double Play - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 9 ---------------

Nick Castellanos - 0.057
Single!
Nick Castellanos hit in 0 runs
Bases - 1B: 12, 2B: None, 3B: None

Alec Bohm - 0.544
---- Double Play - 2 Outs ----

Bryce Harper - 0.654
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 1 ---------------

Bryson Stott - 0.93
---- Flyout - 1 Outs ----

Kyle Schwarber - 0.546
---- Strikeout - 2 Outs ----

Trea Turner - 0.469
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

J.T. Realmuto - 0.749
---- Groundout - 1 Outs ----

Nick Castellanos - 0.649
---- Groundout - 2 Outs ----

Alec Bohm - 0.386
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Bryce Harper - 0.076
Walk!
Bryce Harper hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

Brandon Marsh - 0.242
Single!
Brandon Marsh hit in 0 runs
Bases - 1B: 2, 2B: 1, 3B: None

Johan Rojas - 0.266
Single!
Johan Rojas hit in 0 runs
Bases - 1B: 3, 2B: 2, 3B: 1

Bryson Stott - 0.535
---- Groundout - 1 Outs ----

Kyle Schwarber - 0.8
---- Double Play - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 4 ---------------

Trea Turner - 0.233
Single!
Trea Turner hit in 0 runs
Bases - 1B: 4, 2B: None, 3B: None

J.T. Realmuto - 0.275
---- Strikeout - 1 Outs ----

Nick Castellanos - 0.97
---- Flyout - 2 Outs ----

Alec Bohm - 0.181
Single!
Alec Bohm hit in 0 runs
Bases - 1B: 5, 2B: 4, 3B: None

Bryce Harper - 0.112
Walk!
Bryce Harper hit in 0 runs
Bases - 1B: 6, 2B: 5, 3B: 4

Brandon Marsh - 0.081
Walk!
Brandon Marsh hit in 1 runs
Bases - 1B: 7, 2B: 6, 3B: 5

Johan Rojas - 0.871
---- Groundout - 3 Outs ----

Runs Scored in Inning: 1
Runs Scored in Game: 1


--------------- Inning 5 ---------------

Bryson Stott - 0.543
---- Groundout - 1 Outs ----

Kyle Schwarber - 0.109
Walk!
Kyle Schwarber hit in 0 runs
Bases - 1B: 8, 2B: None, 3B: None

Trea Turner - 0.417
---- Strikeout - 2 Outs ----

J.T. Realmuto - 0.912
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 6 ---------------

Nick Castellanos - 0.413
---- Strikeout - 1 Outs ----

Alec Bohm - 0.89
---- Flyout - 2 Outs ----

Bryce Harper - 0.999
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 7 ---------------

Brandon Marsh - 0.394
---- Strikeout - 1 Outs ----

Johan Rojas - 0.434
---- Strikeout - 2 Outs ----

Bryson Stott - 0.973
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 8 ---------------

Kyle Schwarber - 0.799
---- Groundout - 1 Outs ----

Trea Turner - 0.029
Walk!
Trea Turner hit in 0 runs
Bases - 1B: 9, 2B: None, 3B: None

J.T. Realmuto - 0.41
---- Strikeout - 2 Outs ----

Nick Castellanos - 0.703
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 9 ---------------

Alec Bohm - 0.179
Single!
Alec Bohm hit in 0 runs
Bases - 1B: 10, 2B: None, 3B: None

Bryce Harper - 0.22
Single!
Bryce Harper hit in 0 runs
Bases - 1B: 11, 2B: 10, 3B: None

Brandon Marsh - 0.752
---- Strikeout - 1 Outs ----

Johan Rojas - 0.598
---- Groundout - 2 Outs ----

Bryson Stott - 0.585
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 1 ---------------

Bryson Stott - 0.05
Walk!
Bryson Stott hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

Kyle Schwarber - 0.689
---- Strikeout - 1 Outs ----

Trea Turner - 0.329
Double!
Trea Turner hit in 0 runs
Bases - 1B: None, 2B: 2, 3B: 1

J.T. Realmuto - 0.249
---- Strikeout - 2 Outs ----

Nick Castellanos - 0.512
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

Alec Bohm - 0.843
---- Flyout - 1 Outs ----

Bryce Harper - 0.879
---- Flyout - 2 Outs ----

Brandon Marsh - 0.803
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Johan Rojas - 0.129
Single!
Johan Rojas hit in 0 runs
Bases - 1B: 3, 2B: None, 3B: None

Bryson Stott - 0.443
---- Strikeout - 1 Outs ----

Kyle Schwarber - 0.691
---- Strikeout - 2 Outs ----

Trea Turner - 0.36
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 4 ---------------

J.T. Realmuto - 0.235
---- Strikeout - 1 Outs ----

Nick Castellanos - 0.447
---- Strikeout - 2 Outs ----

Alec Bohm - 0.467
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 5 ---------------

Bryce Harper - 0.906
---- Flyout - 1 Outs ----

Brandon Marsh - 0.256
Single!
Brandon Marsh hit in 0 runs
Bases - 1B: 4, 2B: None, 3B: None

Johan Rojas - 0.396
---- Strikeout - 2 Outs ----

Bryson Stott - 0.441
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 6 ---------------

Kyle Schwarber - 0.889
---- Groundout - 1 Outs ----

Trea Turner - 0.699
---- Groundout - 2 Outs ----

J.T. Realmuto - 0.749
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 7 ---------------

Nick Castellanos - 0.14
Single!
Nick Castellanos hit in 0 runs
Bases - 1B: 5, 2B: None, 3B: None

Alec Bohm - 0.591
---- Double Play - 2 Outs ----

Bryce Harper - 0.95
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 8 ---------------

Brandon Marsh - 0.481
---- Strikeout - 1 Outs ----

Johan Rojas - 0.287
Triple!
Johan Rojas hit in 0 runs
Bases - 1B: None, 2B: None, 3B: 6

Bryson Stott - 0.19
Single!
Bryson Stott hit in 1 runs
Bases - 1B: 7, 2B: None, 3B: None

Kyle Schwarber - 0.923
---- Double Play - 3 Outs ----

Runs Scored in Inning: 1
Runs Scored in Game: 1


--------------- Inning 9 ---------------

Trea Turner - 0.14
Single!
Trea Turner hit in 0 runs
Bases - 1B: 8, 2B: None, 3B: None

J.T. Realmuto - 0.161
Single!
J.T. Realmuto hit in 0 runs
Bases - 1B: 9, 2B: 8, 3B: None

Nick Castellanos - 0.717
---- Groundout - 1 Outs ----

Alec Bohm - 0.455
---- Strikeout - 2 Outs ----

Bryce Harper - 0.376
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 1


--------------- Inning 1 ---------------

Bryson Stott - 0.808
---- Flyout - 1 Outs ----

Kyle Schwarber - 0.51
---- Strikeout - 2 Outs ----

Trea Turner - 0.821
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

J.T. Realmuto - 0.819
---- Groundout - 1 Outs ----

Nick Castellanos - 0.11
Single!
Nick Castellanos hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

Alec Bohm - 0.487
---- Strikeout - 2 Outs ----

Bryce Harper - 0.343
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Brandon Marsh - 0.474
---- Strikeout - 1 Outs ----

Johan Rojas - 0.391
---- Strikeout - 2 Outs ----

Bryson Stott - 0.492
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 4 ---------------

Kyle Schwarber - 0.438
---- Strikeout - 1 Outs ----

Trea Turner - 0.707
---- Groundout - 2 Outs ----

J.T. Realmuto - 0.05
Walk!
J.T. Realmuto hit in 0 runs
Bases - 1B: 2, 2B: None, 3B: None

Nick Castellanos - 0.512
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 5 ---------------

Alec Bohm - 0.187
Single!
Alec Bohm hit in 0 runs
Bases - 1B: 3, 2B: None, 3B: None

Bryce Harper - 0.854
---- Flyout - 1 Outs ----

Brandon Marsh - 0.148
Single!
Brandon Marsh hit in 0 runs
Bases - 1B: 4, 2B: 3, 3B: None

Johan Rojas - 0.863
---- Double Play - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 6 ---------------

Bryson Stott - 0.793
---- Flyout - 1 Outs ----

Kyle Schwarber - 0.462
---- Strikeout - 2 Outs ----

Trea Turner - 0.176
Single!
Trea Turner hit in 0 runs
Bases - 1B: 5, 2B: None, 3B: None

J.T. Realmuto - 0.353
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 7 ---------------

Nick Castellanos - 0.966
---- Flyout - 1 Outs ----

Alec Bohm - 0.965
---- Flyout - 2 Outs ----

Bryce Harper - 0.957
---- Flyout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 8 ---------------

Brandon Marsh - 0.559
---- Strikeout - 1 Outs ----

Johan Rojas - 0.491
---- Strikeout - 2 Outs ----

Bryson Stott - 0.594
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 9 ---------------

Kyle Schwarber - 0.057
Walk!
Kyle Schwarber hit in 0 runs
Bases - 1B: 6, 2B: None, 3B: None

Trea Turner - 0.708
---- Double Play - 2 Outs ----

J.T. Realmuto - 0.724
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 1 ---------------

Bryson Stott - 0.853
---- Flyout - 1 Outs ----

Kyle Schwarber - 0.689
---- Strikeout - 2 Outs ----

Trea Turner - 0.37
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 2 ---------------

J.T. Realmuto - 0.391
---- Strikeout - 1 Outs ----

Nick Castellanos - 0.657
---- Groundout - 2 Outs ----

Alec Bohm - 0.666
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 3 ---------------

Bryce Harper - 0.686
---- Groundout - 1 Outs ----

Brandon Marsh - 0.731
---- Strikeout - 2 Outs ----

Johan Rojas - 0.845
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 4 ---------------

Bryson Stott - 0.041
Walk!
Bryson Stott hit in 0 runs
Bases - 1B: 1, 2B: None, 3B: None

Kyle Schwarber - 0.949
---- Flyout - 1 Outs ----

Trea Turner - 0.841
---- Flyout - 2 Outs ----

J.T. Realmuto - 0.612
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 5 ---------------

Nick Castellanos - 0.529
---- Strikeout - 1 Outs ----

Alec Bohm - 0.885
---- Flyout - 2 Outs ----

Bryce Harper - 0.668
---- Groundout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 6 ---------------

Brandon Marsh - 0.121
Walk!
Brandon Marsh hit in 0 runs
Bases - 1B: 2, 2B: None, 3B: None

Johan Rojas - 0.894
---- Flyout - 1 Outs ----

Bryson Stott - 0.985
---- Flyout - 2 Outs ----

Kyle Schwarber - 0.476
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 7 ---------------

Trea Turner - 0.226
Single!
Trea Turner hit in 0 runs
Bases - 1B: 3, 2B: None, 3B: None

J.T. Realmuto - 0.351
---- Strikeout - 1 Outs ----

Nick Castellanos - 0.318
Error/Fielder's Choice!
Nick Castellanos hit in 0 runs
Bases - 1B: 4, 2B: 3, 3B: None

Alec Bohm - 0.844
---- Flyout - 2 Outs ----

Bryce Harper - 0.426
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 8 ---------------

Brandon Marsh - 0.403
---- Strikeout - 1 Outs ----

Johan Rojas - 0.667
---- Groundout - 2 Outs ----

Bryson Stott - 0.299
---- Strikeout - 3 Outs ----

Runs Scored in Inning: 0
Runs Scored in Game: 0


--------------- Inning 9 ---------------

Kyle Schwarber - 0.004
Walk!
Kyle Schwarber hit in 0 runs
Bases - 1B: 5, 2B: None, 3B: None

Trea Turner - 0.262
Single!
Trea Turner hit in 0 runs
Bases - 1B: 6, 2B: 5, 3B: None

J.T. Realmuto - 0.581